version: '3'

services:

  ansible-control:
    container_name: ansible-control
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    build:
      context: .
      dockerfile: control.Dockerfile
    volumes:
      - ./:/app
    networks:
      - ansible_net
    tty: true

  ansible-node-1:
    container_name: ansible-node-1
    build:
      context: .
      dockerfile: node.Dockerfile
    networks:
      - ansible_net
    ports:
      - 9090:8080
    tty: true

  ansible-node-2:
    container_name: ansible-node-2
    build:
      context: .
      dockerfile: node.Dockerfile
    networks:
      - ansible_net
    ports:
      - 7070:8080
    tty: true

networks:
  ansible_net:
    driver: bridge