- name: This playbook prepares the Ansible control node
  hosts: 127.0.0.1
  connection: local


  tasks:
  - name: Create /root/.ssh folder
    file:
      path: /root/.ssh
      state: directory

  - name: Add nodes to /root/.ssh/known_hosts file
    copy:
      dest: /root/.ssh/known_hosts
      content: |
        ansible-node1
        anisble-node2
